### ISSUE TITLE
eco support cnn+hog+cn features？

### ISSUE THREAD

**Issue by ou-zhi-hui** [rockkingjy/OpenTracker#28]
eco support cnn+hog+cn features？and support cuda,cudnn compile？

**Comment by rockkingjy** [comment]
yes, it suport cnn+hog+cn, and cuda/cudnn things are all in caffe, so it also supports that.

**Comment by ou-zhi-hui** [comment]
so,what dose 🔨 | ECO and 🔨 | GPU | 🔨 | 🔨 means? is there something not finished?
how long does eco takes in tx2 with gpu？
thank you!

**Comment by rockkingjy** [comment]
yes, there are 2 different places using GPU, one is CNN features, that is in Caffe using GPU, it's already done. Another one is, it could also be calculated using GPU by the ECO itself, I've tried, but not help much, because not too much cell calculations needed except CNN features. So the main speed-up by GPU lies in CNN features. You could use it by setting USE_CAFFE=1 in makefile, and Caffe should be installed correctly.

**Comment by ou-zhi-hui** [comment]
okay，i see，so what is eco fps on tx2 with gpu?
and will you support cmake compile in the near future?

**Comment by rockkingjy** [comment]
I haven't test cnn on tx2, you could have a try, it should work.
cmake is in OpenTracker/example, you could use eco simply by using it's library .so,  just need to make install it.

**Comment by rockkingjy** [comment]
just for fun.

**Comment by isgursoy** [comment]
Is there any "working in progress" list for eco?
